In [1]:
#Import Libraries

In [2]:
import pandas as pd
import numpy as np
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split, KFold, LeaveOneOut, cross_val_score
from sklearn.metrics import classification_report
import warnings
warnings.filterwarnings('ignore')


In [3]:
df = pd.read_csv('https://raw.githubusercontent.com/snehuuu28/Machine_Learning/main/Model_Validation/fetal_health.csv')

In [4]:
df.head()

baseline value  accelerations  fetal_movement  uterine_contractions  \
0           120.0          0.000             0.0                 0.000   
1           132.0          0.006             0.0                 0.006   
2           133.0          0.003             0.0                 0.008   
3           134.0          0.003             0.0                 0.008   
4           132.0          0.007             0.0                 0.008   

   light_decelerations  severe_decelerations  prolongued_decelerations  \
0                0.000                   0.0                       0.0   
1                0.003                   0.0                       0.0   
2                0.003                   0.0                       0.0   
3                0.003                   0.0                       0.0   
4                0.000                   0.0                       0.0   

   abnormal_short_term_variability  mean_value_of_short_term_variability  \
0                             73.0                                   0.5   
1                             17.0                                   2.1   
2                             16.0                                   2.1   
3                             16.0                                   2.4   
4                             16.0                                   2.4   

   percentage_of_time_with_abnormal_long_term_variability  ...  histogram_min  \
0                                               43.0       ...           62.0   
1                                                0.0       ...           68.0   
2                                                0.0       ...           68.0   
3                                                0.0       ...           53.0   
4                                                0.0       ...           53.0   

   histogram_max  histogram_number_of_peaks  histogram_number_of_zeroes  \
0          126.0                        2.0                         0.0   
1          198.0                        6.0                         1.0   
2          198.0                        5.0                         1.0   
3          170.0                       11.0                         0.0   
4          170.0                        9.0                         0.0   

   histogram_mode  histogram_mean  histogram_median  histogram_variance  \
0           120.0           137.0             121.0                73.0   
1           141.0           136.0             140.0                12.0   
2           141.0           135.0             138.0                13.0   
3           137.0           134.0             137.0                13.0   
4           137.0           136.0             138.0                11.0   

   histogram_tendency  fetal_health  
0                 1.0           2.0  
1                 0.0           1.0  
2                 0.0           1.0  
3                 1.0           1.0  
4                 1.0           1.0  

[5 rows x 22 columns]

In [5]:
df['fetal_health'].value_counts()

fetal_health
1.0    1655
2.0     295
3.0     176
Name: count, dtype: int64

# Train Test Split

In [7]:
x = df.iloc[:,:-1]
y = df['fetal_health']

In [8]:
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size=0.2, random_state=0)

In [9]:
dt = DecisionTreeClassifier()
dt.fit(xtrain,ytrain)
ypred = dt.predict(xtest)
ypred

array([1., 1., 1., 1., 2., 1., 1., 1., 1., 1., 3., 1., 1., 1., 1., 1., 2.,
       1., 1., 2., 1., 1., 1., 3., 1., 1., 1., 2., 1., 2., 1., 1., 1., 1.,
       1., 1., 2., 1., 3., 1., 1., 2., 1., 1., 2., 1., 1., 1., 1., 1., 1.,
       1., 2., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 2., 1., 1.,
       1., 1., 2., 1., 2., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 2., 1., 1., 1., 2., 1., 1., 1., 1., 2., 1., 1.,
       1., 3., 2., 2., 1., 1., 3., 2., 1., 1., 1., 1., 1., 1., 1., 2., 1.,
       1., 3., 2., 1., 1., 1., 1., 1., 1., 1., 3., 1., 1., 2., 2., 3., 1.,
       2., 1., 1., 1., 1., 1., 1., 2., 2., 2., 3., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 2., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 3., 1., 1., 1., 2., 1., 1., 1., 1., 3.,
       1., 2., 2., 1., 1., 1., 1., 1., 1., 3., 1., 1., 3., 1., 3., 3., 1.,
       3., 1., 1., 1., 1., 2., 1., 1., 1., 3., 1., 1., 1., 1., 2., 1., 1.,
       1., 3., 1., 1., 1.

In [10]:
print(classification_report(ytest,ypred))

              precision    recall  f1-score   support

         1.0       0.96      0.98      0.97       326
         2.0       0.82      0.79      0.81        58
         3.0       0.95      0.88      0.91        42

    accuracy                           0.94       426
   macro avg       0.91      0.88      0.90       426
weighted avg       0.94      0.94      0.94       426



# KFold

In [12]:
kf = KFold(n_splits = 5)
scores = cross_val_score(DecisionTreeClassifier(),x,y, cv= kf)

In [13]:
scores

array([0.85915493, 0.86117647, 0.98588235, 0.83764706, 0.76470588])

In [14]:
scores.mean()         #Accuracy

0.8617133388566695

In [15]:
from sklearn.linear_model import LogisticRegression

lg_scores = cross_val_score(LogisticRegression(),x,y,cv = kf)
print(lg_scores)
lg_scores.mean()

[0.71126761 0.75529412 0.98352941 0.88470588 0.79529412]


0.8260182270091135

In [16]:
from sklearn.ensemble import RandomForestClassifier

kf=KFold(n_splits = 10)
rf_scores = cross_val_score(RandomForestClassifier(),x,y, cv = kf)
rf_scores.mean()

0.8926897865178492

# Leave one out CV

In [18]:
df = pd.read_csv('https://raw.githubusercontent.com/snehuuu28/Machine_Learning/main/Model_Validation/Pima.csv',index_col=0)

In [19]:
df  

preg  plas  pres  skin  test  mass   pedi  age  class
0       6   148    72    35     0  33.6  0.627   50      1
1       1    85    66    29     0  26.6  0.351   31      0
2       8   183    64     0     0  23.3  0.672   32      1
3       1    89    66    23    94  28.1  0.167   21      0
4       0   137    40    35   168  43.1  2.288   33      1
..    ...   ...   ...   ...   ...   ...    ...  ...    ...
763    10   101    76    48   180  32.9  0.171   63      0
764     2   122    70    27     0  36.8  0.340   27      0
765     5   121    72    23   112  26.2  0.245   30      0
766     1   126    60     0     0  30.1  0.349   47      1
767     1    93    70    31     0  30.4  0.315   23      0

[768 rows x 9 columns]

In [20]:
x = df.iloc[:,:-1]
y = df['class']

In [21]:
lv_cv = LeaveOneOut()
lv_score = cross_val_score(DecisionTreeClassifier(),x,y, cv=lv_cv)

In [22]:
lv_score

array([1., 1., 1., 1., 0., 1., 0., 1., 1., 1., 1., 1., 1., 0., 1., 0., 1.,
       1., 1., 0., 1., 0., 1., 0., 0., 1., 0., 1., 0., 1., 1., 1., 1., 1.,
       0., 1., 0., 1., 0., 0., 0., 0., 1., 1., 0., 1., 0., 1., 1., 1., 1.,
       1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 0., 1., 0., 1., 0., 0., 0.,
       1., 1., 0., 0., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 0., 1., 1., 0., 1., 0., 1., 1., 0., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 0., 1., 0., 0., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 0., 1., 1., 1., 0., 0., 0., 1., 1., 1., 1., 1.,
       1., 1., 0., 1., 1., 1., 0., 0., 1., 1., 1., 0., 0., 1., 1., 1., 1.,
       1., 0., 1., 1., 1., 1., 0., 1., 0., 1., 1., 1., 1., 1., 0., 1., 0.,
       0., 0., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 0., 0., 1., 1., 1., 0., 1.,
       1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 1., 0., 1., 0., 0., 1.,
       1., 1., 1., 1., 0.

In [23]:
len(lv_score)

768

In [24]:
lv_score.mean()

0.7109375